appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: LIXAvihTZpkPkd95WgbCap+iqWWaDld7DrwzORPI+k6NS3BQ1/2+5sYgWGBMx+E63yLqg4ch4KTsAI5thFczNQcKjjOBt7lXAJa4nMfbZMCZ/3zRMtsEAF4X2fVEwSuGB7v8sP+gqAnCoCjEQmdQILclD3crEPYgyDtEo62nY9CLhfMwkfRwbni395xn8UP9aersyku+WWV5PUn5QRiCNyAIQfCfC8W9UhEQsMKuFJARq0Zigu0DnKuRBq0NArZB1ClELCxa3nTLfciEP2CbCaneUcbsyMJY/znjwFA3XRZgvRW7RjIYamEYkL0oQ5EV3Yr2eOjio6fWilbj0cysY3lhLMj9D7Kf6Bo4/6JDcZzBBjtci9NYipFmVECwphtLSgGFqF02FppU3P8/h98EFK5UQbu5FmVWl0CxUHUQqvSKB9J0DoJH1cAdHK2wuHAt77ban6GeVke5PErYdotj7mFuR8JnzOi2s7RBuZ71JWzBq6Vzl+Br5vt0xk+lpaMfxgnC9ba6BVWUIuggXickKywUdh7vEqT5s3NzTCDkJwskVH2pgJTY+FrnUd/YTgAjcPAEH6xi4TLmLbKWeoLI/tdmdRyPJ5pgI8zmkp8MKA+ixhqO18zgyGD5DQkMbqgtYSmLCQS4DO+W9GF0wDlVQglJHw1JZPXJYcvh1Pm7bIY=
